spring.application.name=EmbarkX
#h2 connection string
#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:test
##enable sql commands in CMD
#spring.jpa.genarate-ddl=true
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=create-drop
#Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
info.app.name=EbmarkX
info.app.description=This a microservice project
info.app.version=1.0.1
management.info.env.enabled=true
#Postgresql
spring.datasource.url=jdbc:postgresql://localhost:5432/jobapp?options=-c%20TimeZone=Asia/Kolkata
spring.datasource.username=pranay
spring.datasource.password=pranay
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Kolkata
spring.jpa.database=POSTGRESQL
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop

