spring.application.name=EmbarkX
#h2 connection string
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:test
#enable sql commands in CMD
spring.jpa.genarate-ddl=true
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop